# Generated by Django 4.2.20 on 2025-03-29 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('codecat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libcat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('codeprod', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libprod', models.CharField(max_length=100)),
                ('qte', models.IntegerField()),
                ('pu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestcom.categorie')),
            ],
        ),
    ]
